#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|-------------------------------------------------------------------------
| Registre o carregador automático
|--------------------------------------------------------------------------
|
| O Composer fornece um carregador de classe conveniente e gerado automaticamente
| para nosso aplicativo. Só precisamos utilizá-lo! Vamos exigir isso
| no script aqui para que não tenhamos que nos preocupar com o
| carregamento de nenhuma de nossas classes manualmente. É ótimo relaxar.
|
*/

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|-------------------------------------------------------------------------
| Execute o aplicativo Artisan
|--------------------------------------------------------------------------
|
| Quando executarmos o aplicativo de console, o comando CLI atual será
| executado neste console e a resposta será enviada de volta para um terminal
| ou outro dispositivo de saída para os desenvolvedores. Aqui vai nada!
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|-------------------------------------------------------------------------
| Desligar o aplicativo
|--------------------------------------------------------------------------
|
| Assim que o Artisan terminar de executar, dispararemos os eventos de desligamento
| para que qualquer trabalho final possa ser feito pelo aplicativo antes de desligarmos
| o processo. Esta é a última coisa a acontecer com a solicitação.
|
*/

$kernel->terminate($input, $status);

exit($status);
